using Autodesk.AutoCAD.Geometry;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Detailing.Entities
{
    class VerticalCut
    {
        private void DrawHorizontalCut(double elem1, double elem2, Point3d point3D)
        {


        }
        private void DrawLeftSideCut(double elem1, Point3d startPoint) { }
        private void DrawHorizontalMiddle(Point3d startPoint) { }
        private void DrawRigthSideCut(double elem2, Point3d startPoint) { }
        private void DrawVerticalCut()
        {

        }
        private void DrawUpSideCut(double elem3, Point3d startPoint) { }
        private void DrawVerticalMiddle(Point3d startPoint) { }
        private void DrawDownSideCut(double elem4, Point3d startPoint) { }

    }
}
